apiVersion:v1
kind: ServiceAccount
metadata:
    name:mongodb
    labels:
      app:mongodb
spec:
  clusterIP: None
  selector:
    app: mongodb
  ports:
    -port: 27017
     targetport:27017
namespace: database
    Secrets:
       -name: mongodb
